BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
TRAINER_NAME: d3diffuser 
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/tensorboard_dirs/d3diffuser_da
CHECKPOINT_FOLDER: data/checkpoints/d3diffuser_da
EVAL_CKPT_PATH_DIR: data/checkpoints/d3diffuser_da/ckpt.100.pth
RESULTS_DIR: data/checkpoints/d3diffuser_da/evals
VIDEO_OPTION: []
lr_Schedule: False
dagger: True


EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen # for testing overfitting only
  EPISODE_COUNT: -1
  ACTION_POP: True

IL:
  ckpt_to_load: data/checkpoints/d3diffuser_da/ckpt.8.pth
  load_from_ckpt: True # for testing overfitting only 
  epochs: 4
  batch_size: 20
  is_requeue: False # continuo training
  

  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz
    
  DAGGER:
    iterations: 10
    update_size: 5000
    p: 0.75
    preload_lmdb_features: False
    lmdb_features_dir: data/trajectories_dirs/d3diffuser_da/trajectories.lmdb
    
    

DIFFUSER:
  embedding_dim: 256
  num_attention_heads: 8
  num_layers: 4
  diffusion_timesteps: 100
  logging_file: data/loggings/train.log
  saving_frequency: 20
  LR: 2.5e-4
  traj_length: 3
  beta: 0.1 
  action_space: 4
  traj_space: 4

MODEL:
  policy_name: D3DiffusionPolicy

  INSTRUCTION_ENCODER:
    bidirectional: True


