BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
TRAINER_NAME: diffuser 
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/tensorboard_dirs/diffuser
CHECKPOINT_FOLDER: data/checkpoints/diffuser
EVAL_CKPT_PATH_DIR: data/checkpoints/diffuser/ckpt.800.pth
RESULTS_DIR: data/checkpoints/diffuser/evals
VIDEO_OPTION: []

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_seen # for testing overfitting only
  EPISODE_COUNT: -1
  ACTION_POP: True

IL:
  ckpt_to_load: data/checkpoints/diffuser/ckpt.800.pth
  load_from_ckpt: False # for testing overfitting only
  epochs: 2000
  batch_size: 128
  is_requeue: False # continuo training
  

  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz
    
  DAGGER:
    iterations: 1
    update_size: 10819
    p: 1.0
    preload_lmdb_features: True
    lmdb_features_dir: data/trajectories_dirs/diffuser/trajectories.lmdb
    
    

DIFFUSER:
  embedding_dim: 256
  num_attention_heads: 4
  num_layers: 4
  diffusion_timesteps: 100
  logging_file: data/loggings/train.log
  LR: 1.0e-5
  traj_length: 3
  beta: 0.1
  action_space: 4
  traj_space: 4

MODEL:
  policy_name: DiffusionPolicy

  INSTRUCTION_ENCODER:
    bidirectional: True


