BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task_aug.yaml
TRAINER_NAME: diffuser
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/tensorboard_dirs/diffuser_aug
CHECKPOINT_FOLDER: data/checkpoints/diffuser_aug
EVAL_CKPT_PATH_DIR: data/checkpoints/diffuser_aug
RESULTS_DIR: data/checkpoints/diffuser_aug/evals

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

IL:
  epochs: 1000
  batch_size: 32

  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz
    
  DAGGER:
    iterations: 1
    update_size: 157232
    p: 1.0
    preload_lmdb_features: False
    lmdb_features_dir: data/trajectories_dirs/diffuser_aug/trajectories.lmdb

DIFFUSER:
  embedding_dim: 256
  num_attention_heads: 4
  num_layers: 2
  diffusion_timesteps: 1000
  logging_file: data/loggings/train.log
  LR: 1.0e-3

MODEL:
  policy_name: DiffusionPolicy

  INSTRUCTION_ENCODER:
    bidirectional: True


