BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task_aug_L40.yaml
TRAINER_NAME: openvln_trainer_fsdp
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 1
NUM_PROCESSES: 1
TENSORBOARD_DIR: data/tensorboard_dirs/openvln_fsdp_nofilmalign_dagger_ft
CHECKPOINT_FOLDER: data/checkpoints/openvln_fsdp_nofilmalign_dagger_ft
EVAL_CKPT_PATH_DIR: data/checkpoints/openvln_fsdp_nofilmalign_dagger_ft/ckpt.4.pth
RESULTS_DIR: data/checkpoints/openvln_fsdp_nofilmalign_dagger_ft/evals
VIDEO_OPTION: []
JobName: openvln_fsdp_nofilmalign_dagger_ft
lr_Schedule: True
dagger: True


EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen # for testing overfitting only
  EPISODE_COUNT: -1
  ACTION_POP: True

IL:
  ckpt_to_load: data/checkpoints/openvln_fsdp_nofilm/ckpt.24.pth
  load_from_ckpt: False 
  epochs: 10
  batch_size: 32 # global bs
  is_requeue: False 
  training: False

  

  RECOLLECT_TRAINER:
    gt_file:
      /mnt/nfs/sgyson10/data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz
    
  DAGGER:
    iterations: 1
    update_size: 22500 # 15000 + 7500
    p: 0.10
    preload_lmdb_features: True
    lmdb_features_dir: data/trajectories_dirs/nofilmalign_dagger/trajectories.lmdb
    lmdb_commit_frequency: 50
    
    

OPENVLN:
  saving_frequency: 1
  logging_file: data/loggings/train.log
  LR: 2.5e-5
  stage: "finetune" 
  # stage: training stage in < "align" | "finetune" | "full-finetune" >
  forward_type: "pre-train"
  # forward_type: in < "action_only" | "pre-train"  >
  flash_atten: True
  phase: "phii"
  truncation: True # whether to apply truncation on timesteps
  film: False

MODEL:
  policy_name: OpenVLNPolicy

TYPE: VLN-CE-v1
SPLIT: joint_train_envdrop
DATA_PATH: /mnt/nfs/sgyson10/data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}.json.gz
SCENES_DIR: /mnt/nfs/sgyson10/data/scene_datasets/